name: Run tests
on:
  push:
    branches: [main]
  pull_request:
  create:

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        py: ["3.11", "3.10", "3.9", "3.8", "3.7"]

    runs-on: ${{ matrix.os }}
    name: Run test with Python ${{ matrix.py }} on ${{ matrix.os }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ matrix.py }}
          cache: "pip"

      - name: Build
        shell: bash
        run: |
          pip install -r requirements.txt pytest
          make cython
          pip install .

      - name: Test (C extension)
        shell: bash
        run: |
          pytest -v test

      - name: Test (pure Python fallback)
        shell: bash
        run: |
          MSGPACK_PUREPYTHON=1 pytest -v test
